## Numpy Exercise - Part B

## Array Creation

In [2]:
import numpy as np

In [3]:
A = np.array([[1,6,4], [4,9,8], [3,7,1]])

## 1.MIN

In [4]:
def min(a):
    min_elem = (0, 0)
    min_val = a[0][0]
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (a[i][j] < min_val):
                min_val = a[i][j]
                min_elem = (i, j)
    return min_val

In [5]:
min(A)

1

## 2.MAX

In [6]:
def max(a):
    max_elem = (0, 0)
    max_val = a[0][0]
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (a[i][j] > max_val):
                max_val = a[i][j]
                max_elem = (i, j)
    return max_val

In [7]:
max(A)

9

## 3.MEAN

In [8]:
def mean(a):
    sum_val = 0
    a_num = a.shape[0]*a.shape[1]
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            sum_val += a[i][j]
    mean_val = float(sum_val)/a_num
    return mean_val

In [9]:
mean(A)

4.777777777777778

## 4.ARGMIN

In [10]:
def argmin(a):
    min_elem = (0, 0)
    min_val = a[0][0]
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (a[i][j] < min_val):
                min_val = a[i][j]
                min_elem = (i, j)
    return min_elem

In [11]:
argmin(A)

(0, 0)

## 5.ARGMAX

In [12]:
def argmax(a):
    max_elem = (0, 0)
    max_val = a[0][0]
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (a[i][j] > max_val):
                max_val = a[i][j]
                max_elem = (i, j)
    return max_elem

In [13]:
argmax(A)

(1, 1)

## 6.FLATTEN

In [14]:
def flatten(a):
    flat_lst = []
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            flat_lst.append(a[i][j])
    return np.asarray(flat_lst)

In [16]:
flatten(A)

array([1, 6, 4, 4, 9, 8, 3, 7, 1])

## 7.RAVEL

In [19]:
def ravel(a):
    rvl_lst = []
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            rvl_lst.append(a[i][j])
    return np.asarray(rvl_lst)

In [20]:
ravel(A)

array([1, 6, 4, 4, 9, 8, 3, 7, 1])

## 8.DOT PRODUCT

In [21]:
def my_dot(a, b):
    dot_product = []
    row_dot = []
    dim1 = a.shape
    dim2 = b.shape
    if len(dim1) < 2:
        a = a.reshape(1, dim1[0])
    if len(dim2) < 2:
        b = b.reshape(1, dim2[0])
    row1, column1 = a.shape
    row2, column2 = b.shape
    result = np.zeros((row1, column2), dtype=np.int)
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
               result[i][j] += a[i][k] * b[k][j]
    return np.array(result)

In [22]:
b = np.array([[1 ,0 ,0 ],[0 ,1 ,0 ],[0 ,0 ,1]])

In [23]:
my_dot(A, b)

array([[1, 6, 4],
       [4, 9, 8],
       [3, 7, 1]])

## 9.* for Matrix (Element wise multiplication)

In [25]:
def product(a,b):
    c = []
    for i in list(range(len(a))):
        w = []
        for j in list(range(len(a[0]))):
                w.append(a[i][j] * b[i][j]) 
        c.append(w)     
    return(c)

In [26]:
product(A ,b)

[[1, 12, 12], [16, 45, 48], [21, 56, 9]]

## 10.Arange Followed By Reshape

In [27]:
def arangen(n):
    return(list(range(n)))

In [28]:
arangen(5)

[0, 1, 2, 3, 4]

In [30]:
def reshapen(x ,r ,c):
    ca = []
    k = 0
    for i in list(range(r)):
        w = []
        for j in list(range(c)):
                w.append(x[k])
                k = k + 1
        ca.append(w)        
    return(ca)

In [31]:
reshapen([1 ,2 ,3 ,4 ,5 ,6],2 ,3)

[[1, 2, 3], [4, 5, 6]]

## 11.Identity/Eye

In [32]:
def iden(dim):
    list_main=[]
    for i in range(dim):
        list_temp=[]
        for j in range(dim):
            if(i==j):
                list_temp.append(1)
            else:
                list_temp.append(0)
        list_main.append(list_temp)
    return np.asarray(list_main)

In [33]:
iden(4)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
def eye(row, col):
    list_main=[]
    for i in range(row):
        list_temp=[]
        for j in range(col):
            if(i==j):
                list_temp.append(1)
            else:
                list_temp.append(0)
        list_main.append(list_temp)
    return np.asarray(list_main)

In [35]:
eye(4,5)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

## 12.SUM

In [36]:
def sum(a):
    sum_val = 0
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            sum_val += a[i][j]
    return sum_val

In [37]:
sum(A)

43

## 13.DIAG

In [38]:
def diag(a):
    diag_list = []
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (i == j):
                diag_list.append(a[i][j])
    return np.asarray(diag_list)

In [39]:
diag(A)

array([1, 9, 1])

## 14.TRIL/TRIU

In [40]:
def tril(a):
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (i > j):
                a[i][j] = 0
    return a

In [41]:
tril(A)

array([[1, 6, 4],
       [0, 9, 8],
       [0, 0, 1]])

In [42]:
def triu(a):
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if (i < j):
                a[i][j] = 0
    return a

In [43]:
triu(A)

array([[1, 0, 0],
       [0, 9, 0],
       [0, 0, 1]])