## Numpy Exercises

## Part - A

#### Make use of the following inbuilt api's
1. min
2. max
2. mean
3. argmin
4. argmax
5. linalg.solve
6. flatten
7. ravel
8. dot Product
9. \* for Matrix (Element wise multiplication)
10. arange followed by reshape
11. identity / eye
12. sum
13. diag
14. tril / triu

## Part - B

#### For the all api's mentioned above implement your own version of it. Except linalg.solve. At minimum each implementation of yours should support 2d matrices.


## Numpy - Part A (Solution)

In [2]:
import numpy as np

In [3]:
sample_arr = np.arange(20).reshape(4,5)

In [13]:
sample_arr.min(axis=0)

array([0, 1, 2, 3, 4])

In [14]:
sample_arr.max(axis=1)

array([ 4,  9, 14, 19])

In [19]:
sample_arr.mean(axis=1)

array([  2.,   7.,  12.,  17.])

In [21]:
sample_arr.argmin(axis=1)

array([0, 0, 0, 0])

In [23]:
sample_arr.argmax(axis=0)

array([3, 3, 3, 3, 3])

In [26]:
mat1 = np.array([[2,5], [9,3]])
mat2 = np.array([3,7])
sol1 = np.linalg.solve(mat1, mat2)
sol1

array([ 0.66666667,  0.33333333])

In [34]:
sample_flat = sample_arr.flatten(order='C')
sample_flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
sample_ravel = sample_arr.ravel(['C'])
sample_ravel

/home/user/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
  if __name__ == '__main__':


array([ 0,  5, 10, 15,  1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,
        9, 14, 19])

In [39]:
a = np.array([[2,4], [3,7]])
b = np.array([[1,9], [6,1]])
a.dot(b)

array([[26, 22],
       [45, 34]])

In [40]:
a*b

array([[ 2, 36],
       [18,  7]])

In [42]:
another_arr = np.arange(12).reshape(4,3)
another_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
id_arr = np.identity(4)
id_arr

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [48]:
eye_arr = np.eye(2,4)
eye_arr

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.]])

In [53]:
sample_arr.sum(axis=0)

array([30, 34, 38, 42, 46])

In [55]:
sample_arr.diagonal(offset=1)

array([ 1,  7, 13, 19])

In [58]:
np.tril(sample_arr, k=0)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0],
       [10, 11, 12,  0,  0],
       [15, 16, 17, 18,  0]])

In [70]:
np.triu(sample_arr, k=0)

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14],
       [ 0,  0,  0, 18, 19]])